version: 0.2
 
phases:
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn global add @quasar/cli
      - quasar build
      - aws cloudfront create-invalidation --distribution-id EF3TAG75C9SEN --paths "/*";
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist/spa